config/routes.rb
Rails.application.routes.draw do
  resources :menu_items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get 'about_us' => 'home#about_us'
  get 'menu' => 'home#menu'
  get 'user_orders' => 'home#user_orders'
  post 'user_orders' => 'home#checkout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  scope :section, -> (section) { where section: section}
end

app/models/user_order.rb
class UserOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_us
  end

  def menu
    if params[:section].present? then
      order_by = "name ASC"
      if params[:order_value].present? then
        order_by = "#{params[:order_key]} #{params[:order_value]}"
      end
      @menu_items = MenuItem.where(nil)
      @menu_items = @menu_items.section(params[:section]).order(order_by)
      @section = params[:section]
    else
      @menu_items = MenuItem.all
    end
  end

  def user_orders
    @menu_item = MenuItem.find(params[:menu_item])
    @order_item = UserOrder.new
    @order_item.item_name = @menu_item.name
    @order_item.price = @menu_item.price
    @order_item.order_id = Time.now.to_i
  end

def checkout
  @order_item = UserOrder.new(user_orders_params)
end

def user_orders_params
  params.require(:user_order).permit(:order_id, :price, :item_name, :user_name, :user_phone, :user_address)
end

end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to @menu_item, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_item_params
      params.require(:menu_item).permit(:name, :description, :price, :section, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/home/_menu_item.html.erb
<% @menu_items.each do |menu_item| %>
<div class="row card-row">
  <div class="col-xs-12 col-sm-6 col-md-6" style="padding: 1px;">
    <%= image_tag menu_item.image_url, width: '100%' , alt: 'About Us'%>
  </div>
  <div class="col-xs-12 col-xs-6 col-md-6">
    <div clas="info-box">
      <div class="info-box-title">
        <%= menu_item.name %>
      </div>
      <div class="info-box-content">
        <p>
          <%= menu_item.description %>
        </p>
        <div class="menu-price">
          VND <%= menu_item.price %>
        </div>
      </div>
      <div class="info-box-footer  center">
        <%= link_to 'Add to order', user_orders_path(menu_item: menu_item), class: 'btn' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/home/about_us.html.erb
<div class="container-fluid">
  <div class="row card-row" >
    <div class="col-xs-12 col-sm-6 col-md-6" style="padding: 0;">
      <%= image_tag 'about_us.jpg', width: '100%', alt: 'About Us'%>
    </div>
    <div class="col-xs-6 col-md-6">
      <div clas="info-box">
        <div class="info-box-title">
          About Us
        </div>
        <div class="info-box-content">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci di dunt ut labore et dolore magna aliqua.
            Ut enim ad minim reprehenderit veniam. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          </p>
        </div>
        <div class="info-box-footer address-info">
          <p> Visit us at:
          <address>
          Restaurant De Ruby<br>
          167, Dien Bien Phou<br>
          District 1, HCMC<br>
          Phone: <a href="tel:1-847-555-5555">1-847-555-5555 <%= image_tag 'phone.png', size:'20x20' %></a>
          </address>
        </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row card-row" style="margin-top:5px">
    <div class="col-md-12" style="padding: 0;">
      <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d7837.752397859328!2d106.67522900000003!3d10.820785099999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1468119532135" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</div>

app/views/home/checkout.html.erb
<div class="row card-row">
  <div class="col-xs-12 col-xs-6 col-md-6 checkout">
    <div clas="info-box">
      <div class="info-box-title">
        Thank You for Your Order!
      </div>
      <div class="info-box-content">
        <p>
          Name : <%= @order_item.item_name %>
        </p>
        <p>
          Price: <%= @order_item.price %> + (Delivery Charge : VND 20,000)
        </p>
        <p>
          Customer Name : <%= @order_item.user_name %>
        </p>
        <p>
          Customer Address : <%= @order_item.user_address %>
        </p>
        <p>
          Ordered at : <%= Time.now %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row card-row">
    <div class="col-xs-12 col-sm-6 col-md-6" style="padding: 1px;">
      <%= image_tag 'index_menu.jpg', width: '100%' , alt: 'About Us'%>
    </div>
    <div class="col-xs-12 col-xs-6 col-md-6">
      <div clas="info-box">
        <div class="info-box-title">
          Menu
        </div>
        <div class="info-box-content">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci di dunt ut labore et dolore magna aliqua.
            Ut enim ad minim reprehenderit veniam. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          </p>
        </div>
        <div class="info-box-footer  center">
          <%= link_to 'Explore Menu', menu_path, class: 'btn' %>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <div class="row card-row">
    <div class="col-xs-12 col-xs-6 col-md-6">
      <div clas="info-box">
        <div class="info-box-title">
          About Us
        </div>
        <div class="info-box-content">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor inci di dunt ut labore et dolore magna aliqua.
            Ut enim ad minim reprehenderit veniam. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          </p>
        </div>
        <div class="info-box-footer  center">
          <%= link_to 'Find About Us', about_us_path, class: 'btn center' %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6" style="padding: 1px;">
      <%= image_tag 'index_about.jpg', width: '100%', alt: 'About Us'%>
    </div>
  </div>
</div>

app/views/home/menu.html.erb
<div class="menu-section">
  <div style="display: inline-block">
    <h3>
      <%= link_to 'Breakfast', menu_path(section:'breakfast'), class:"label lable-menu-section #{'selected-section' if @section.to_s == 'breakfast'}", style:"margin-right: 40px;" %>
      <%= link_to 'Lunch', menu_path(section:'lunch'), class:"label lable-menu-section #{'selected-section' if @section.to_s == 'lunch'}", style:"margin-right: 40px;" %>
      <%= link_to 'Dinner', menu_path(section:'dinner'), class:"label lable-menu-section #{'selected-section' if @section.to_s == 'dinner'}", style:"margin-right: 40px;" %>
      <%= link_to 'Drink', menu_path(section:'drinks'), class:"label lable-menu-section #{'selected-section' if @section.to_s == 'drinks'}" %>
    </h3>
  </div>
  <div class="btn-group" style="float:right;">
    <button type="button" class="btn btn-default">Sort By</button>
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu">
      <%= link_to 'Name: A-Z', menu_path(section: @section, order_key: 'name', order_value: 'ASC'), class:"dropdown-item" %>
      <%= link_to 'Name: Z-A', menu_path(section: @section, order_key: 'name', order_value: 'DESC'), class:"dropdown-item" %>
      <%= link_to 'Price: Low First', menu_path(section: @section, order_key: 'price', order_value: 'ASC'), class:"dropdown-item" %>
      <%= link_to 'Price: High First', menu_path(section: @section, order_key: 'price', order_value: 'DESC'), class:"dropdown-item" %>
    </div>
  </div>
</div>

<%= render 'menu_item' %>

app/views/home/user_orders.html.erb
<div class="row card-row">
  <div class="col-xs-12 col-sm-6 col-md-6" style="padding: 1px;">
    <%= image_tag @menu_item.image_url, width: '100%' , alt: 'About Us'%>
  </div>
  <div class="col-xs-12 col-xs-6 col-md-6">
    <div clas="info-box">
      <div class="info-box-title">
        <%= @menu_item.name %>
      </div>
      <div class="info-box-content">
        <p>
          <%= @menu_item.description %>
        </p>
        <div class="menu-price">
          VND <%= @menu_item.price %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row card-row">
  <%= bootstrap_form_for(@order_item) do |f| %>
    <%= f.text_field :item_name, :value => @menu_item.name, :readonly => true %>
    <%= f.text_field :price, :value => @menu_item.price, :readonly => true %>
    <%= f.text_field :user_name %>
    <%= f.text_field :user_phone %>
    <%= f.text_area :user_address %>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurent De Ruby</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Oleo+Script' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="page-title">Restaurent De Ruby</div>
  <div class="page-body">
    <div class="page-nav" style="padding-bottom:10px;">
      <nav class="navbar navbar-default page-navbar">
        <ul class="nav navbar-nav">
          <li class="nav-item <%= 'active' if current_page?(root_path) %> ">
            <%= link_to 'Home', root_path , class: 'nav-link'%>
          </li>
          <li class="nav-item <%= 'active' if current_page?(menu_path) %>">
            <%= link_to 'Menu', menu_path , class: 'nav-link'%>
          </li>
          <li class="nav-item <%= 'active' if current_page?(about_us_path) %>">
            <%= link_to 'About Us', about_us_path , class: 'nav-link'%>
          </li>
        </ul>
      </nav>
    </div>
      <%= yield %>
  </div>
</body>
</html>

app/views/menu_items/_form.html.erb
<%= form_for(menu_item) do |f| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
      <% menu_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :section %>
    <%= f.text_field :section %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Show', @menu_item %> |
<%= link_to 'Back', menu_items_path %>

app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menu Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_items.each do |menu_item| %>
      <tr>
        <td><%= menu_item.name %></td>
        <td><%= menu_item.description %></td>
        <td><%= menu_item.price %></td>
        <td><%= menu_item.section %></td>
        <td><%= menu_item.image_url %></td>
        <td><%= link_to 'Show', menu_item %></td>
        <td><%= link_to 'Edit', edit_menu_item_path(menu_item) %></td>
        <td><%= link_to 'Destroy', menu_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu Item', new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item %>

<%= link_to 'Back', menu_items_path %>

app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @menu_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @menu_item.section %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @menu_item.image_url %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>